/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct in {
	int a;
	int b;
};
typedef struct in in;

#define RPC_SERVER 0x3012225
#define CALCULADORA 1

#if defined(__STDC__) || defined(__cplusplus)
#define soma 1
extern  int * soma_1(in *, CLIENT *);
extern  int * soma_1_svc(in *, struct svc_req *);
#define mult 2
extern  int * mult_1(in *, CLIENT *);
extern  int * mult_1_svc(in *, struct svc_req *);
#define div 3
extern  int * div_1(in *, CLIENT *);
extern  int * div_1_svc(in *, struct svc_req *);
#define max 4
extern  int * max_1(in *, CLIENT *);
extern  int * max_1_svc(in *, struct svc_req *);
#define min 5
extern  int * min_1(in *, CLIENT *);
extern  int * min_1_svc(in *, struct svc_req *);
extern int rpc_server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define soma 1
extern  int * soma_1();
extern  int * soma_1_svc();
#define mult 2
extern  int * mult_1();
extern  int * mult_1_svc();
#define div 3
extern  int * div_1();
extern  int * div_1_svc();
#define max 4
extern  int * max_1();
extern  int * max_1_svc();
#define min 5
extern  int * min_1();
extern  int * min_1_svc();
extern int rpc_server_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_in (XDR *, in*);

#else /* K&R C */
extern bool_t xdr_in ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
